import tseslint from 'typescript-eslint';
import eslint from '@eslint/js';
import reactPlugin from 'eslint-plugin-react';
import reactHooksPlugin from 'eslint-plugin-react-hooks';

export default tseslint.config(
  eslint.configs.recommended,
  ...tseslint.configs.recommended,
  {
    ignores: [
      '**/__tests__/**',
      '**/*.test.ts',
      '**/*.test.tsx',
      '**/*.spec.ts',
      '**/*.spec.tsx',
      'dist/**',
      'dist-protected/**',
      'vibe-engine-docs/**',
      'node_modules/**',
      'Universal-Docs/**',
      'coverage/**',
      'brain/**',
      'docs/**',
      'downloads/**',
      'electron-main/**',
      'projects/**',
      'scripts/**',
      '.git/**',
      '.vscode/**',
      '**/*.json',
      '**/*.md',
      '**/*.html',
      '**/*.bat',
      '**/*.sh',
      '**/*.yaml',
      '**/*.yml',
      '**/*.png',
      '**/*.jpg',
      '**/*.jpeg',
      '**/*.gif',
      '**/*.svg',
      '**/*.ico',
      '**/*.ttf',
      '**/*.woff',
      '**/*.woff2',
      '**/*.eot',
      '**/*.mp3',
      '**/*.wav',
      '**/*.ogg',
      '**/*.mp4',
      '**/*.webm',
      '**/*.glb',
      '**/*.gltf',
      '**/*.fbx',
      '**/*.obj',
      '**/*.blend',
      '**/*.dae',
      '**/*.stl',
      '**/*.ply',
      '**/*.3ds',
      '**/*.max',
      '**/*.ma',
      '**/*.mb',
      '**/*.psd',
      '**/*.ai',
      '**/*.sketch',
      '**/*.fig',
      '**/*.xd',
      '**/*.pdf',
      '**/*.doc',
      '**/*.docx',
      '**/*.xls',
      '**/*.xlsx',
      '**/*.ppt',
      '**/*.pptx',
      '**/*.zip',
      '**/*.rar',
      '**/*.7z',
      '**/*.tar',
      '**/*.gz',
      '**/*.bz2',
      '**/*.xz',
      '**/*.log',
      '**/*.tmp',
      '**/*.bak',
      '**/*.swp',
      '**/*.swo',
      '**/*.DS_Store',
      '**/*.Thumbs.db',
      '**/*.lock',
      '**/*.pid',
      '**/*.sock',
    ],
  },
  {
    files: ['src/**/*.{ts,tsx}'],
    plugins: {
      react: reactPlugin,
      'react-hooks': reactHooksPlugin,
    },
    languageOptions: {
      parserOptions: {
        ecmaFeatures: { jsx: true },
      },
    },
    rules: {
      'react/react-in-jsx-scope': 'off',
      '@typescript-eslint/no-explicit-any': 'warn',
      '@typescript-eslint/no-unused-vars': ['warn', { argsIgnorePattern: '^_' }],
      'no-console': 'off',
      'max-lines': ['warn', { max: 500, skipBlankLines: true, skipComments: true }],
    },
  },
  {
    files: ['src/**/*.{test,spec}.{ts,tsx}'],
    rules: {
      '@typescript-eslint/no-explicit-any': 'off',
      'max-lines': 'off',
    },
  },
);