

import { createVibeStyles, VibeTheme } from '@themes/VibeStyles';

export const menuBarStyles = createVibeStyles({
    container: {
        display: 'flex',
        alignItems: 'center',
        height: '48px',
        background: VibeTheme.colors.glassBg,
        backdropFilter: 'blur(30px) saturate(160%)',
        WebkitBackdropFilter: 'blur(30px) saturate(160%)',
        borderBottom: `1px solid ${VibeTheme.colors.glassBorder}`,
        padding: '0 20px',
        userSelect: 'none',
        zIndex: 2000,
        position: 'relative',
    },
    leftSection: {
        flex: 1,
        display: 'flex',
        alignItems: 'center',
        gap: '4px',
    },
    centerSection: {
        flex: 1,
        display: 'flex',
        justifyContent: 'center',
        alignItems: 'center',
    },
    rightSection: {
        flex: 1,
        display: 'flex',
        justifyContent: 'flex-end',
        alignItems: 'center',
        gap: '12px',
    },
    trigger: {
        padding: '6px 14px',
        borderRadius: '8px',
        cursor: 'pointer',
        fontSize: '13px',
        fontWeight: 600,
        color: VibeTheme.colors.textSecondary,
        transition: 'all 0.2s cubic-bezier(0.4, 0, 0.2, 1)',
        position: 'relative',
    },
    triggerActive: {
        background: 'rgba(255, 255, 255, 0.08)',
        color: VibeTheme.colors.textMain,
    },
    playbackGroup: {
        display: 'flex',
        alignItems: 'center',
        gap: '8px',
        background: 'rgba(0,0,0,0.2)',
        padding: '4px 8px',
        borderRadius: '12px',
        border: `1px solid ${VibeTheme.colors.glassBorder}`,
    },
    dropdown: {
        position: 'absolute',
        top: '100%',
        left: '0',
        minWidth: '220px',
        background: VibeTheme.colors.bgSecondary,
        backdropFilter: 'blur(40px)',
        border: `1px solid ${VibeTheme.colors.glassBorder}`,
        borderRadius: '10px',
        padding: '8px',
        zIndex: 3000,
        marginTop: '8px',
        boxShadow: '0 25px 50px -12px rgba(0, 0, 0, 0.5)',
    },
    menuItem: {
        display: 'flex',
        alignItems: 'center',
        padding: '10px 14px',
        borderRadius: '8px',
        cursor: 'pointer',
        fontSize: '13px',
        color: VibeTheme.colors.textSecondary,
        transition: 'all 0.15s ease',
    },
    menuItemHover: {
        background: VibeTheme.colors.accent,
        color: '#fff',
    },
    dividerVertical: {
        width: '1px',
        height: '24px',
        background: VibeTheme.colors.glassBorder,
        margin: '0 4px',
    },
    divider: {
        height: '1px',
        background: VibeTheme.colors.border,
        margin: '8px 4px',
    },
    sceneBadge: {
        fontSize: '11px',
        fontWeight: 700,
        color: VibeTheme.colors.textMain,
        background: VibeTheme.colors.bgSubtle,
        padding: '4px 12px',
        borderRadius: '4px',
        border: `1px solid ${VibeTheme.colors.border}`,
        display: 'flex',
        alignItems: 'center',
        gap: '6px',
    }
});
