

import { createVibeStyles, VibeTheme } from '@themes/VibeStyles';

export const scriptStyles = createVibeStyles({
    panel: {
        display: 'flex',
        flexDirection: 'column',
        height: '100%',
        background: VibeTheme.colors.bgPrimary, 
        overflow: 'hidden',
        position: 'relative',
    },
    header: {
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'space-between',
        padding: '0 8px',
        height: '40px',
        background: VibeTheme.colors.bgSubtle,
        borderBottom: `1px solid ${VibeTheme.colors.glassBorder}`,
        backdropFilter: 'blur(10px)',
        zIndex: 50,
    },
    tabs: {
        display: 'flex',
        alignItems: 'center',
        flex: 1,
        overflowX: 'auto',
        height: '100%',
    },
    tab: {
        display: 'flex',
        alignItems: 'center',
        gap: '8px',
        padding: '0 18px',
        height: '100%',
        color: VibeTheme.colors.textSecondary,
        fontSize: '11px',
        fontWeight: 500,
        letterSpacing: '0.02em',
        whiteSpace: 'nowrap',
        cursor: 'pointer',
        borderRight: `1px solid ${VibeTheme.colors.glassBorder}`,
        transition: 'all 0.2s cubic-bezier(0.4, 0, 0.2, 1)',
        position: 'relative',
        userSelect: 'none',
        opacity: 0.7,
    },
    tabActive: {
        background: VibeTheme.colors.bgPrimary,
        color: VibeTheme.colors.accent,
        opacity: 1,
        boxShadow: `inset 0 -2px 0 ${VibeTheme.colors.accent}`,
    },
    tabHover: {
        background: 'rgba(255, 255, 255, 0.03)',
        color: VibeTheme.colors.textMain,
        opacity: 1,
    },
    dirtyDot: {
        width: '6px',
        height: '6px',
        borderRadius: '50%',
        background: '#f59e0b',
        boxShadow: '0 0 8px rgba(245, 158, 11, 0.5)',
    },
    closeBtn: {
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'center',
        width: '18px',
        height: '18px',
        borderRadius: '50%',
        transition: 'all 0.2s cubic-bezier(0.4, 0, 0.2, 1)',
        opacity: 0.4,
        color: 'inherit',
        marginLeft: '10px',
        border: 'none',
        background: 'transparent',
        cursor: 'pointer',
    },
    closeBtnHover: {
        background: 'rgba(255, 255, 255, 0.08)',
        opacity: 1,
    },
    editorContainer: {
        flex: 1,
        position: 'relative',
        overflow: 'hidden',
        background: VibeTheme.colors.bgPrimary, 
    },
    emptyState: {
        flex: 1,
        display: 'flex',
        flexDirection: 'column',
        alignItems: 'center',
        justifyContent: 'center',
        gap: '16px',
        color: VibeTheme.colors.textSecondary,
        textAlign: 'center',
    },
    badge: {
        fontSize: '11px',
        fontWeight: 700,
        color: VibeTheme.colors.accent,
        background: 'rgba(99, 102, 241, 0.1)',
        padding: '2px 8px',
        borderRadius: '4px',
        border: `1px solid rgba(99, 102, 241, 0.2)`,
    }
});
