import { createVibeStyles, VibeTheme } from '@themes/VibeStyles';

export const viewportStyles = createVibeStyles({
    panel: {
        position: 'relative',
        width: '100%',
        height: '100%',
        background: VibeTheme.colors.bgPrimary,
        overflow: 'hidden',
        display: 'flex',
        flexDirection: 'column',
        cursor: 'crosshair',
    },
    canvas: {
        width: '100%',
        height: '100%',
        display: 'block',
        outline: 'none',
    },
    overlay: {
        position: 'absolute',
        top: 0,
        left: 0,
        right: 0,
        bottom: 0,
        pointerEvents: 'none',
        display: 'flex',
        flexDirection: 'column',
        justifyContent: 'space-between',
    },
    topBar: {
        display: 'flex',
        justifyContent: 'space-between',
        alignItems: 'flex-start',
        padding: '12px 16px',
        pointerEvents: 'auto',
    },
    bottomBar: {
        display: 'flex',
        justifyContent: 'space-between',
        alignItems: 'flex-end',
        padding: '12px 16px',
        pointerEvents: 'auto',
    },
    watermark: {
        position: 'absolute',
        top: '50%',
        left: '50%',
        transform: 'translate(-50%, -50%)',
        fontSize: '14px',
        fontWeight: 300,
        letterSpacing: '16px',
        color: 'rgba(255,255,255,0.04)',
        textTransform: 'uppercase',
        pointerEvents: 'none',
        userSelect: 'none',
        fontFamily: "'Inter', sans-serif",
        whiteSpace: 'nowrap',
    },
    liveIndicator: {
        display: 'flex',
        alignItems: 'center',
        gap: '8px',
        padding: '6px 12px',
        background: 'rgba(239, 68, 68, 0.15)',
        backdropFilter: 'blur(10px)',
        WebkitBackdropFilter: 'blur(10px)',
        border: '1px solid rgba(239, 68, 68, 0.3)',
        borderRadius: '20px',
    },
    liveDot: {
        width: '8px',
        height: '8px',
        borderRadius: '50%',
        background: '#ef4444',
        boxShadow: '0 0 8px rgba(239, 68, 68, 0.8)',
    },
    liveText: {
        fontSize: '10px',
        fontWeight: 700,
        letterSpacing: '1px',
        color: '#ef4444',
        textTransform: 'uppercase',
        fontFamily: "'JetBrains Mono', monospace",
    },
    pausedIndicator: {
        display: 'flex',
        alignItems: 'center',
        gap: '8px',
        padding: '6px 12px',
        background: 'rgba(245, 158, 11, 0.15)',
        backdropFilter: 'blur(10px)',
        WebkitBackdropFilter: 'blur(10px)',
        border: '1px solid rgba(245, 158, 11, 0.3)',
        borderRadius: '20px',
    },
    pausedText: {
        fontSize: '10px',
        fontWeight: 700,
        letterSpacing: '1px',
        color: '#f59e0b',
        textTransform: 'uppercase',
        fontFamily: "'JetBrains Mono', monospace",
    },
    cameraInfo: {
        display: 'flex',
        flexDirection: 'column',
        alignItems: 'flex-end',
        gap: '6px',
    },
    cameraBadge: {
        display: 'flex',
        alignItems: 'center',
        gap: '6px',
        padding: '4px 10px',
        background: 'rgba(59, 130, 246, 0.1)',
        backdropFilter: 'blur(10px)',
        WebkitBackdropFilter: 'blur(10px)',
        border: '1px solid rgba(59, 130, 246, 0.2)',
        borderRadius: '16px',
        fontSize: '10px',
        fontWeight: 600,
        color: '#60a5fa',
        fontFamily: "'JetBrains Mono', monospace",
    },
    viewModeBadge: {
        display: 'flex',
        alignItems: 'center',
        gap: '6px',
        padding: '4px 10px',
        background: 'rgba(16, 185, 129, 0.1)',
        backdropFilter: 'blur(10px)',
        WebkitBackdropFilter: 'blur(10px)',
        border: '1px solid rgba(16, 185, 129, 0.2)',
        borderRadius: '16px',
        fontSize: '10px',
        fontWeight: 600,
        color: '#10b981',
        fontFamily: "'JetBrains Mono', monospace",
        textTransform: 'uppercase',
    },
    performanceHud: {
        display: 'flex',
        flexDirection: 'column',
        alignItems: 'flex-end',
        gap: '4px',
        padding: '8px 14px',
        background: VibeTheme.colors.glassBg,
        backdropFilter: 'blur(30px) saturate(180%)',
        WebkitBackdropFilter: 'blur(30px) saturate(180%)',
        border: `1px solid ${VibeTheme.colors.glassBorder}`,
        borderRadius: '14px',
        minWidth: '120px',
        boxShadow: '0 8px 32px rgba(0, 0, 0, 0.2)',
    },
    performanceRow: {
        display: 'flex',
        justifyContent: 'space-between',
        alignItems: 'center',
        gap: '12px',
    },
    performanceLabel: {
        fontSize: '9px',
        color: 'rgba(255,255,255,0.4)',
        fontFamily: "'JetBrains Mono', monospace",
        textTransform: 'uppercase',
        letterSpacing: '0.5px',
    },
    performanceValue: {
        fontSize: '10px',
        fontWeight: 700,
        fontFamily: "'JetBrains Mono', monospace",
        textAlign: 'right',
    },
    performanceValueGood: {
        color: '#10b981',
    },
    performanceValueWarn: {
        color: '#f59e0b',
    },
    performanceValueBad: {
        color: '#ef4444',
    },
    sceneInfo: {
        display: 'flex',
        flexDirection: 'column',
        alignItems: 'flex-start',
        gap: '6px',
        padding: '8px 14px',
        background: VibeTheme.colors.glassBg,
        backdropFilter: 'blur(30px) saturate(180%)',
        WebkitBackdropFilter: 'blur(30px) saturate(180%)',
        border: `1px solid ${VibeTheme.colors.glassBorder}`,
        borderRadius: '14px',
        minWidth: '140px',
        boxShadow: '0 8px 32px rgba(0, 0, 0, 0.2)',
    },
    sceneInfoRow: {
        display: 'flex',
        justifyContent: 'space-between',
        alignItems: 'center',
        gap: '12px',
    },
    selectionInfo: {
        display: 'flex',
        flexDirection: 'column',
        alignItems: 'flex-start',
        gap: '4px',
        padding: '8px 12px',
        background: 'rgba(59, 130, 246, 0.1)',
        backdropFilter: 'blur(10px)',
        WebkitBackdropFilter: 'blur(10px)',
        border: '1px solid rgba(59, 130, 246, 0.2)',
        borderRadius: '10px',
        minWidth: '140px',
    },
    selectionName: {
        fontSize: '11px',
        fontWeight: 600,
        color: '#60a5fa',
        fontFamily: "'JetBrains Mono', monospace",
    },
    selectionType: {
        fontSize: '9px',
        color: 'rgba(96, 165, 250, 0.6)',
        fontFamily: "'JetBrains Mono', monospace",
        textTransform: 'uppercase',
    },
    gridInfo: {
        display: 'flex',
        alignItems: 'center',
        gap: '6px',
        padding: '4px 10px',
        background: 'rgba(255, 255, 255, 0.05)',
        backdropFilter: 'blur(10px)',
        WebkitBackdropFilter: 'blur(10px)',
        border: '1px solid rgba(255, 255, 255, 0.08)',
        borderRadius: '16px',
        fontSize: '10px',
        color: 'rgba(255,255,255,0.5)',
        fontFamily: "'JetBrains Mono', monospace",
    },
    raceHUD: {
        position: 'absolute',
        bottom: '80px',
        left: '50%',
        transform: 'translateX(-50%)',
        display: 'flex',
        alignItems: 'center',
        gap: '40px',
        padding: '24px 48px',
        background: 'rgba(10, 10, 20, 0.4)',
        backdropFilter: 'blur(30px) saturate(200%)',
        WebkitBackdropFilter: 'blur(30px) saturate(200%)',
        border: '1px solid rgba(255, 255, 255, 0.1)',
        borderRadius: '30px',
        boxShadow: '0 20px 50px rgba(0, 0, 0, 0.4)',
        pointerEvents: 'none',
        zIndex: 100,
    },
    raceHUDItem: {
        display: 'flex',
        flexDirection: 'column',
        alignItems: 'center',
    },
    raceHUDValue: {
        fontSize: '32px',
        fontWeight: 800,
        color: '#ffffff',
        fontFamily: "'Inter', sans-serif",
        fontVariantNumeric: 'tabular-nums',
    },
    raceHUDLabel: {
        fontSize: '10px',
        fontWeight: 700,
        color: 'rgba(255, 255, 255, 0.4)',
        textTransform: 'uppercase',
        letterSpacing: '2px',
        marginTop: '4px',
    },
    speedometerUnit: {
        fontSize: '14px',
        fontWeight: 500,
        color: 'rgba(255, 255, 255, 0.6)',
        marginLeft: '4px',
    },
    focusIndicator: {
        position: 'absolute',
        top: '50%',
        left: '50%',
        transform: 'translate(-50%, -50%)',
        width: '20px',
        height: '20px',
        pointerEvents: 'none',
    },
    focusCrosshairH: {
        position: 'absolute',
        top: '50%',
        left: '50%',
        transform: 'translate(-50%, -50%)',
        width: '20px',
        height: '1px',
        background: 'rgba(255, 255, 255, 0.3)',
    },
    focusCrosshairV: {
        position: 'absolute',
        top: '50%',
        left: '50%',
        transform: 'translate(-50%, -50%)',
        width: '1px',
        height: '20px',
        background: 'rgba(255, 255, 255, 0.3)',
    },
});

export const viewportAnimations = `
    @keyframes live-pulse {
        0% { transform: scale(0.95); box-shadow: 0 0 0 0 rgba(239, 68, 68, 0.7); }
        70% { transform: scale(1.1); box-shadow: 0 0 0 10px rgba(239, 68, 68, 0); }
        100% { transform: scale(0.95); box-shadow: 0 0 0 0 rgba(239, 68, 68, 0); }
    }
    
    @keyframes focus-pulse {
        0%, 100% { opacity: 0.3; }
        50% { opacity: 0.8; }
    }
    
    @keyframes slide-in-top {
        from { transform: translateY(-10px); opacity: 0; }
        to { transform: translateY(0); opacity: 1; }
    }
    
    @keyframes slide-in-bottom {
        from { transform: translateY(10px); opacity: 0; }
        to { transform: translateY(0); opacity: 1; }
    }
    
    @keyframes fade-in {
        from { opacity: 0; }
        to { opacity: 1; }
    }
`;